-- ffi_typedef.lua
local ffi = require("ffi")
ffi.cdef[[
typedef void *PVOID;
typedef void *LPVOID;
typedef int BOOL;
typedef BOOL *PBOOL;
typedef BOOL *LPBOOL;
typedef char CHAR;
typedef char *PSZ;
typedef unsigned char UCHAR;
typedef UCHAR *PUCHAR;
typedef unsigned char BYTE;
typedef BYTE *PBYTE;
typedef BYTE *LPBYTE;
typedef int INT;
typedef int *PINT;
typedef int *LPINT;
typedef unsigned int UINT;
typedef unsigned int *PUINT;
typedef short SHORT;
typedef short *PSHORT;
typedef unsigned short USHORT;
typedef USHORT *PUSHORT;
typedef unsigned short WORD;
typedef WORD *PWORD;
typedef WORD *LPWORD;
typedef long LONG;
typedef long *PLONG;
typedef long *LPLONG;
typedef unsigned long ULONG;
typedef ULONG *PULONG;
typedef unsigned long DWORD;
typedef DWORD *PDWORD;
typedef DWORD *LPDWORD;
typedef float FLOAT;
typedef FLOAT *PFLOAT;
typedef wchar_t WCHAR;
typedef WCHAR *PWCHAR,*LPWCH,*PWCH;
typedef const WCHAR *LPCWCH,*PCWCH;
typedef WCHAR *NWPSTR,*LPWSTR,*PWSTR;
typedef PWSTR *PZPWSTR;
typedef const PWSTR *PCZPWSTR;
typedef const WCHAR *LPCWSTR,*PCWSTR;
typedef PCWSTR *PZPCWSTR;
typedef CHAR *PCHAR,*LPCH,*PCH;
typedef const CHAR *LPCCH,*PCCH;
typedef CHAR *NPSTR,*LPSTR,*PSTR;
typedef PSTR *PZPSTR;
typedef const PSTR *PCZPSTR;
typedef const CHAR *LPCSTR,*PCSTR;
typedef PCSTR *PZPCSTR;
]];
